// Generated by CoffeeScript 1.7.1
(function() {
  $.extend($.fn, {
    'ichecku': function() {
      var el, ickecku, init, update;
      el = $(this).hide();
      ickecku = $('<div class="ichecku off"><div class="circle"></div></div>');
      init = function() {
        if (el.is(':checked')) {
          ickecku.removeClass('off');
          return ickecku.addClass('on');
        }
      };
      update = function() {
        if (ickecku.is('.on')) {
          return el.attr('checked', 'checked');
        } else {
          return el.removeAttr('checked');
        }
      };
      ickecku.find('.circle').bind('click', function() {
        ickecku.toggleClass('on');
        return update();
      });
      return ickecku.insertBefore(el);
    }
  });

}).call(this);
